# Generated by Django 4.2.3 on 2023-08-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('financial_measure', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.DeleteModel(
            name='CashAndCashEquiv',
        ),
        migrations.DeleteModel(
            name='EBIT',
        ),
        migrations.DeleteModel(
            name='EBITDA',
        ),
        migrations.DeleteModel(
            name='GrossProfit',
        ),
        migrations.DeleteModel(
            name='Liabilities',
        ),
    ]
