# Generated by Django 4.2.3 on 2023-08-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_api', '0002_financialdata_delete_assets_delete_cashandcashequiv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdata',
            name='company',
        ),
    ]
